version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    target-branch: bankdata/v0.7.0
    schedule:
      interval: weekly
    labels:
      - dependencies
    commit-message:
      prefix: "⬆️"
    groups:
      go-patch:
        patterns:
          - "*"
        update-types:
          - patch
