name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24 # Adjust the Go version as needed

      - name: Run Makefile target `go-test`
        run: make go-test

      - name: Run Makefile target `authz-test`
        run: make authz-test

      - name: Run Makefile target `library-test`
        run: make library-test

      - name: Run Makefile target `go-e2e-migrate-test`
        env:
          GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
          GITHUB_PASSWORD: ${{ secrets.GH_PASSWORD }}
          STYRA_TOKEN: ${{ secrets.STYRA_TOKEN }}
          STYRA_TOKEN_2: ${{ secrets.STYRA_TOKEN_2 }}
          STYRA_TOKEN_3: ${{ secrets.STYRA_TOKEN_3 }}
          BACKTEST_MAX_EVAL_TIME_INFLATION: -1
        run: make go-e2e-migrate-test
